apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads-stage/sbaird-tenant/devfile-sample/devfile-sample@sha256:7df9cfbc8f20ccab069afda0e10b16450964191cf517bdb875b5dc8cf5b75b7b
        name: my-nodejs
        resources: {}
status: {}
